AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Demonstrates using a built-in Node.js module to send messages to FIFO queue with duplicated ID.
Parameters: 
    IdentityNameParameter: 
      Type: String
Resources:
  httpsrequest:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: Demonstrates using a built-in Node.js module to send messages to FIFO queue with duplicated ID.
      MemorySize: 128
      Timeout: 60
      Policies:
        - SESSendBouncePolicy:
            IdentityName: !Ref IdentityNameParameter
